name: Deploy To-Do App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2   # v2 artık destekleniyor
        with:
          path: './todo-app'

      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
upload-pages-artifact@v2
